"""M-Pesa port and deterministic FakeAdapter (ADR 0004, ADR 0006). No network access."""

from mpesa import b2c_result_codes
from mpesa.errors import (
    CallbackAuthenticityError,
    CallbackMalformedError,
    ChargeDeclinedError,
    DisbursementRejectedError,
    DuplicateOriginatorConversationError,
    MpesaError,
    OutcomeUnknownError,
    UnknownReferenceError,
)
from mpesa.fake_adapter import (
    MAGIC_MSISDNS,
    CallbackDelivery,
    DuplicateInitiateError,
    FakeAdapter,
    FakeAdapterConfig,
    ManualClock,
    Scenario,
)
from mpesa.fake_disbursement import MAGIC_RECIPIENTS, B2CScenario
from mpesa.models import (
    MAX_DISBURSEMENT_MINOR,
    MIN_DISBURSEMENT_MINOR,
    CallbackEvent,
    ChargeAccepted,
    ChargeRequest,
    DeclineReason,
    DisbursementAccepted,
    DisbursementEvent,
    DisbursementRequest,
    DisbursementStatus,
    FailureReason,
    Outcome,
    PaymentStatus,
)
from mpesa.port import DisbursementPort, MpesaPort

__all__ = [
    "MAGIC_MSISDNS",
    "MAGIC_RECIPIENTS",
    "MAX_DISBURSEMENT_MINOR",
    "MIN_DISBURSEMENT_MINOR",
    "B2CScenario",
    "CallbackAuthenticityError",
    "CallbackDelivery",
    "CallbackEvent",
    "CallbackMalformedError",
    "ChargeAccepted",
    "ChargeDeclinedError",
    "ChargeRequest",
    "DeclineReason",
    "DisbursementAccepted",
    "DisbursementEvent",
    "DisbursementPort",
    "DisbursementRejectedError",
    "DisbursementRequest",
    "DisbursementStatus",
    "DuplicateInitiateError",
    "DuplicateOriginatorConversationError",
    "FailureReason",
    "FakeAdapter",
    "FakeAdapterConfig",
    "ManualClock",
    "MpesaError",
    "MpesaPort",
    "Outcome",
    "OutcomeUnknownError",
    "PaymentStatus",
    "Scenario",
    "UnknownReferenceError",
    "b2c_result_codes",
]
